services:
  app:
    build: .
    ports:
      - "5173:5173" # Web frontend
      - "3001:3001" # Server API
      - "8080:8080" # Linera faucet
      - "9001:9001" # Linera shard proxy
      - "13001:13001" # Linera shard
    volumes:
      - .:/build
